AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a secure S3 bucket with versioning, encryption, and public access blocked."

Resources:
  # This is the logical ID for our S3 bucket resource.
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      # Using !Sub with ${AWS::AccountId} creates a globally unique bucket name,
      # which is required for S3. You can change 'my-secure-bucket' to your desired name.
      BucketName: !Sub "my-secure-bucket-${AWS::AccountId}-${AWS::Region}"

      # This section is critical for security. It blocks all forms of public access.
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      # Enabling versioning is a best practice to protect against accidental
      # data overwrites or deletions.
      VersioningConfiguration:
        Status: Enabled

      # This enables default server-side encryption using Amazon S3-managed keys (SSE-S3).
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      # Tags are useful for cost allocation, automation, and organization.
      Tags:
        - Key: "ManagedBy"
          Value: "CloudFormation"
        - Key: "Purpose"
          Value: "Application Data Storage"

Outputs:
  # The Outputs section makes it easy to find and use the created resource's information.
  BucketName:
    Description: "The name of the newly created S3 bucket."
    Value: !Ref S3Bucket
    Export:
      # Exporting the value allows other CloudFormation stacks to reference this bucket.
      Name: !Sub "${AWS::StackName}-BucketName"

  BucketARN:
    Description: "The ARN (Amazon Resource Name) of the S3 bucket."
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketARN"