AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a secure S3 bucket with versioning and encryption enabled."

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "my-app-data-${AWS::AccountId}-nf-aws-upskilling"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: "The name of the S3 bucket."
    Value: !Ref S3Bucket
  BucketARN:
    Description: "The ARN of the S3 bucket."
    Value: !GetAtt S3Bucket.Arn
